### PR TITLE
FUSETOOLS-1983 - adding new template for eap-spring

### PR DESCRIPTION
**Pull request by bfitzpat**
I  cannot get my categories to show up no matter what I do. What am I missing? I'm guessing it's something simple.

### CODE REVIEW

**Comment by apupier** [comment]
Need to include IT test for all templates to avoid regressions: see FuseIntegrationProjectCreatorRunnableIT and its implementatiosn classes

**Comment by lhein** [comment]
whats up with that PR? its hard to see what changed at all. Something is really wrong with your formatting / eclipse settings, Brian? Could you fix that and update the PR?

**Comment by apupier** [comment]
@bfitzpat you should try to create your branches on origin/master , it allows to be more up-to-date with latest commits

**Comment by apupier** [comment]
@bfitzpat I provided a PR on your branch fixing your issue of the template not displayed: https://github.com/bfitzpat/fuseide/pull/1

**Comment by lhein** [comment]
+1

**Pull request merged**
