### PR TITLE
FUSETOOLS-2999 - fixing validation

### PR DESCRIPTION
**Pull request by bfitzpat**
Signed-off-by: Brian Fitzpatrick <bfitzpat@redhat.com>

# Pull Request Checklist

After this checklist is all checked or PR provides explanations for possible pass-through, please put the label "Ready for review" on the PR.

## General

- [ ] Did you use the Jira Issue number in the commit comments?
- [ ] Did you set meaningful commit comments on each commit?
- [ ] Did you sign off all commits for this PR? (git commit -s -m "jira issue number - your commit comment")

## Functional

- [ ] Did the CI job report a successful build?
- [ ] Is the non-happy path working, too?

## Maintainability

- [ ] Are all Sonar reported issues fixed or can they be ignored?
- [ ] Is there no duplicated code?
- [ ] Are method-/class-/variable-names meaningful?

## Tests

- [ ] Are there unit-tests?
- [ ] Are there integration tests (or at least a jira to tackle these)?
- [ ] Do we need a new UI test?

## Legal

- [ ] Have you used the correct file header copyright comment?
- [ ] Have you used the correct year in the headers of new files?

### CODE REVIEW

**Comment by bfitzpat** [comment]
Will try and repro here. Thanks.

**Comment by bfitzpat** [comment]
Can definitely reproduce here. I'm adding a type delay (WidgetProperties.text(SWT.Modify).observeDelayed(500, control)) to help with it a bit, but the ultimate issue seems to come from a SAX parsing issue with the WSDL referenced at the URL you're trying...
```
WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://nullege.com/codes/search/SOAPpy.WSDL'.: org.xml.sax.SAXParseException: The reference to entity "f" must end with the ';' delimiter.
WSDLException: faultCode=PARSER_ERROR: Problem parsing 'http://nullege.com/codes/search/SOAPpy.WSDL'.: org.xml.sax.SAXParseException: The reference to entity "f" must end with the ';' delimiter.
```

Any suggestions on how to better/more efficiently process the contents of the URL? Ultimately there are two parts to this validation - one simply ensures that it's not empty and is a valid URL; two then tries to parse the WSDL to find the service location. It's this second part where we're getting hung up in WSDL2RestWizardBasePage.getLocationFromWSDL().

@apupier

**Comment by apupier** [comment]
> Any suggestions on how to better/more efficiently process the contents of the URL?

My first suggestion would be to validate only when it is empty as a first iteration.
To validate if the wsdl is valid, I would say that the validation needs to be launched asynchronously (but makes message status harder to handle)
In "New Fuse Integration Wizard", the validation of camel version can take time, it is then done on-demand via button and when clicking finish.

**Comment by bfitzpat** [comment]
Hmm. I'll take a look at it again today. Thanks for the suggestions.

**Comment by bfitzpat** [comment]
With the validation tweak in place, parsing becomes VERY fast and the issue goes away.

**Comment by apupier** [comment]
Now the validation is just checking hat the URL is valid

image

can be enough for a first iteration

**Comment by bfitzpat** [comment]
Even before, we didn't fully validate the WSDL, only that the field was not blank and the URL was accessible. Are you proposing a third validation where we somehow validate that it's valid WSDL or a valid XML file? That would be a great check, but I'm honestly not sure that the time required would be worth the cost. The SAX parser (without the validation tweaks I made yesterday) takes several seconds to throw back an invalid result for some reason and would still show up as potentially "hung" if we went that route.

**Comment by apupier** [comment]
> Are you proposing a third validation where we somehow validate that it's valid WSDL or a valid XML file?

that's a possibility. Maybe not worthy enough given time to develop it.

I also wanted to check that I understood the expected behavior correctly.

**Pull request merged**
