### PR TITLE
FUSETOOLS-1970 - Ensure a build has been done before searching in Java

### PR DESCRIPTION
**Pull request by apupier**
classpath

- also wait for Refresh Build finished to avoid some "Resource out of
sync" even if no issue detected from that, except trace in log
- also provide the monitor and declare it as Done, the creator of the
monitor is reponsible for that.

### CODE REVIEW

**Comment by apupier** [comment]
@lhein and @bfitzpat as it is an asynchronous issue, can you test it on your machine?

**Comment by bfitzpat** [comment]
Ok. I've tried with three different examples and it works fine if you go from a perspective other than the Git perspective and do a Maven project import. However, if in the Git perspective you drill into the git repo path, right click on a Java DSL fuse project and select "Import Maven Projects" from the popup menu - it somehow does not add the Camel facet still.

**Comment by bfitzpat** [comment]
I'm not sure what's different about that particular triggering of the maven project import, but it does not work fully with the Camel project configurator automatically adding the camel facet.

**Comment by apupier** [comment]
ok, do you agree to merge this branch and open another JIRA issue to mange the import from git perspective?

**Comment by bfitzpat** [comment]
+1 to that. sounds like a plan

**Comment by bfitzpat** [comment]
Spun off FUSETOOLS-1973

**Pull request merged**
