### PR TITLE
Improve AMQ Template Description

### PR DESCRIPTION
**Pull request by apupier**
image

image

### CODE REVIEW

**Comment by apupier** [comment]
waiting feedback from Jane

**Comment by jcmurphey** [comment]
Assume the user is an inexperienced newbie. Must the name of the pid file be camel.activemq.blueprint.conf? Do they put it in the JBoss Fuse installation's /etc dir? Does the file have other required structure or formatting elements. If so provide a more complete example. A colon (:) at end of 2nd bulleted item will clarify the following sentence contains the name of the bundle to install.
I am confused too. Where does this bundle come from? Doesn't the user build the project using the Fuse Tooling? Why wouldn't the user run it from inside the tooling?

**Comment by jcmurphey** [comment]
One more thing...provide a link pointing directly to the relevant information on the camel.apache.org web site.

**Comment by apupier** [comment]
> Assume the user is an inexperienced newbie. Must the name of the pid file be camel.activemq.blueprint.conf? Do they put it in the JBoss Fuse installation's /etc dir?

Yes, I modified the sentence trying to be clearer.

> Does the file have other required structure or formatting elements. If so provide a more complete example.

no

> A colon (:) at end of 2nd bulleted item will clarify the following sentence contains the name of the bundle to install.

done

> I am confused too. Where does this bundle come from? Doesn't the user build the project using the Fuse Tooling? Why wouldn't the user run it from inside the tooling?

From Fuse "magic"...
I wanted to provide a text for running inside the IDE but the answer was "we don't have the time. it's not the priority".
i created a specific issue as we must do it for every templates: https://issues.jboss.org/browse/FUSETOOLS-2057

so now we have:
image

image

**Comment by jcmurphey** [comment]
Hummmm, is this also the case for the new Spring on EAP template? That there is no script for running it from inside the tooling?

**Comment by apupier** [comment]
> Hummmm, is this also the case for the new Spring on EAP template? That there is no script for running it from inside the tooling?

I don't understand your question. There is no script to run for nothing.

In the ReadMe.Txt, there is an explanation on how to run the Camel Route in JBoss Fuse or on Fuse on EAP. There is no explanation on how to launch it graphically from the tooling (this part will be covered by  https://issues.jboss.org/browse/FUSETOOLS-2057 )

**Comment by jcmurphey** [comment]
Wrong word...I meant a provided text for running inside the tooling- same issue as for activemq template

**Comment by apupier** [comment]
ok, so it is what is planned to be covered by https://issues.jboss.org/browse/FUSETOOLS-2057

**Pull request merged**
