### PR TITLE
FUSETOOLS-1331 - Update to ensure that start page in Fuse Transform

### PR DESCRIPTION
**Pull request by bfitzpat**
wizard prevents Finishing in actual "unfinished" state

### CODE REVIEW

**Comment by kcbabo** [comment]
Looks like there is still a hole here.  Using the starter project:
- New Fuse Transformation 
- Supply all required details and select XML -> JSON
- Click Next
- Fill out XML details
- Click Next
- Fill out JSON details
- Click Back twice to return to first page
- Change target type to Java
- Click Next
- Can't click Next to move to Java target page

**Comment by bfitzpat** [comment]
This  has me lost a bit and I'll tackle it again in the morning. Sorry. :(

**Comment by bfitzpat** [comment]
@kcbabo After a lot of arm wrestling, I have updated the PR and it works backwards and forwards now. The only thing I'm not quite happy with is the way the model viewer (on the Java and Other pages) gets reset, but I'm hopeful @jpav can offer a way to reset the viewer to a null state that I can take advantage of. 

Right now I create an empty model (https://github.com/fusesource/fuseide/pull/310/files#diff-d8b5a05e95cd87921df68d7a3950e8a8R304) and set that on the viewer. (I do that on both pages currently.) If I don't, it caches the last model that was stashed in there and it may be a stale/incorrect representation of the class the user chooses. 

However... You can change source or target or both and the wizard is much happier now. 

Can you give it a shot?

**Comment by bfitzpat** [comment]
I have tested numerous ways back and forth and all seems good... I have tried
* Empty -> XML (Schema) to JSON (Schema)
* JSON (Instance) to XML (Schema) -> Changed JSON to Java
* Java to XML (Schema) -> Changed Java to JSON (Schema) -> Changed XML to Java
* Other to Other -> Changed Other (Source) to XML (Schema)

Please let me know if you find anything wacky.

**Comment by kcbabo** [comment]
Worked for me!

**Comment by kcbabo** [comment]
pushed to master and 7.3.x

**Pull request closed without merging**
