### PR TITLE
Fusetools 2262 handle camelversion not supported exactly

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
the remaining issue is that when adding a Language or DataFormat, the dependency will be the one from the closest compatible camel version and not the exact one specified in the pom.xml for camel-core

**Comment by apodhrad** [comment]
I tried it locally and it seems to be working

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Pull request merged**
