### PR TITLE
Integration Test requires to follow *IT pattern

### PR DESCRIPTION
**Pull request by apupier**
otherwise they are not played during build

### CODE REVIEW

**Comment by bfitzpat** [comment]
I'll take a look.

**Comment by apupier** [comment]
for faster investigation, here is the test in error:

> 12:26:59 testEAPSpringProjectCreation[2.17.0.redhat-630077](org.fusesource.ide.projecttemplates.tests.integration.wizards.FuseIntegrationProjectCreatorRunnableForEAPSpringIT)  Time elapsed: 20.303 sec  <<< FAILURE!
12:26:59 java.lang.AssertionError: 
12:26:59 Expecting:
12:26:59  <true>
12:26:59 to be equal to:
12:26:59  <false>
12:26:59 but was not.
12:26:59 	at org.fusesource.ide.projecttemplates.tests.integration.wizards.FuseIntegrationProjectCreatorRunnableForEAPSpringIT.checkCorrectFacetsEnabled(FuseIntegrationProjectCreatorRunnableForEAPSpringIT.java:73)

**Comment by apupier** [comment]
for

> assumeFalse("Spring with 2.15 redhat version is not working", camelVersion.startsWith("2.15"));

Are you sure? In other examples the isseu was with Blueprint. Spring 2.15 doesn't work on EAP?

**Comment by apupier** [comment]
stacktrace in log which seems to be the root cause:

> 11:41:11.421 [main] WARN  o.e.m.c.p.c.AbstractLifecycleMapping - Could not update project FuseIntegrationProjectCreatorRunnableForEAPSpringIT-EAPSpringProject-2.17.0.redhat-630077 configuration
java.lang.IllegalArgumentException: null
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectWorkingCopy.removeProjectFacet(FacetedProjectWorkingCopy.java:876) ~[na:na]
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject$1.run(FacetedProject.java:309) ~[na:na]
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241) ~[org.eclipse.core.resources_3.10.1.v20150725-1910.jar:na]
	at org.eclipse.wst.common.project.facet.core.internal.FacetedProject.modify(FacetedProject.java:339) ~[na:na]
	at org.eclipse.m2e.wtp.WebProjectConfiguratorDelegate.configure(WebProjectConfiguratorDelegate.java:133) ~[na:na]
	at org.eclipse.m2e.wtp.AbstractProjectConfiguratorDelegate.configureProject(AbstractProjectConfiguratorDelegate.java:94) ~[na:na]
	at org.eclipse.m2e.wtp.WTPProjectConfigurator.configure(WTPProjectConfigurator.java:71) ~[na:na]
	at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120) ~[org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:501) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:494) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:281) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$4.run(ProjectConfigurationManager.java:521) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.embedder.AbstractRunnable.call(AbstractRunnable.java:26) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.embedder.AbstractRunnable.call(AbstractRunnable.java:1) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.enableMavenNature(ProjectConfigurationManager.java:518) [org.eclipse.m2e.core_1.6.3.20160209-1446.jar:na]
	at org.fusesource.ide.projecttemplates.adopters.configurators.MavenTemplateConfigurator.configureMavenNature(MavenTemplateConfigurator.java:77) [org.fusesource.ide.projecttemplates/:na]
	at org.fusesource.ide.projecttemplates.adopters.configurators.MavenTemplateConfigurator.configure(MavenTemplateConfigurator.java:51) [org.fusesource.ide.projecttemplates/:na]
	at org.fusesource.ide.projecttemplates.adopters.AbstractProjectTemplate.create(AbstractProjectTemplate.java:58) [org.fusesource.ide.projecttemplates/:na]
	at org.fusesource.ide.projecttemplates.wizards.FuseIntegrationProjectCreatorRunnable.run(FuseIntegrationProjectCreatorRunnable.java:96) [org.fusesource.ide.projecttemplates/:na]
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:463) [org.eclipse.jface_3.11.1.v20160128-1644.jar:na]
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:371) [org.eclipse.jface_3.11.1.v20160128-1644.jar:na]
	at org.eclipse.jface.dialogs.ProgressMonitorDialog.run(ProgressMonitorDialog.java:500) [org.eclipse.jface_3.11.1.v20160128-1644.jar:na]
	at org.fusesource.ide.projecttemplates.tests.integration.wizards.FuseIntegrationProjectCreatorRunnableIT.testProjectCreation(FuseIntegrationProjectCreatorRunnableIT.java:131) [org.fusesource.ide.projecttemplates.tests.integration/:na]
	at org.fusesource.ide.projecttemplates.tests.integration.wizards.FuseIntegrationProjectCreatorRunnableForEAPSpringIT.testEAPSpringProjectCreation(FuseIntegrationProjectCreatorRunnableForEAPSpringIT.java:49) [org.fusesource.ide.projecttemplates.tests.integration/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91-3-redhat]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91-3-redhat]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91-3-redhat]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91-3-redhat]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit.jar:4.12]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit.jar:4.12]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit.jar:4.12]
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48) [junit.jar:4.12]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:128) [junit.jar:4.12]
	at org.junit.runners.Suite.runChild(Suite.java:27) [junit.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit.jar:4.12]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) [org.eclipse.jdt.junit4.runtime_1.1.500.v20150423-0747.jar:na]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) [org.eclipse.jdt.junit.runtime_3.4.500.v20140527-1138.jar:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459) [org.eclipse.jdt.junit.runtime_3.4.500.v20140527-1138.jar:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675) [org.eclipse.jdt.junit.runtime_3.4.500.v20140527-1138.jar:na]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382) [org.eclipse.jdt.junit.runtime_3.4.500.v20140527-1138.jar:na]
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:62) [org.eclipse.pde.junit.runtime_3.4.500.v20150423-1241.jar:na]
	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness$1.run(PlatformUITestHarness.java:47) [org.eclipse.pde.junit.runtime_3.4.500.v20150423-1241.jar:na]
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35) [org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar:na]
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135) [org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar:na]
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155) [org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772) [org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar:na]
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827) [org.eclipse.jface_3.11.1.v20160128-1644.jar:na]
	at org.eclipse.jface.window.Window.open(Window.java:803) [org.eclipse.jface_3.11.1.v20160128-1644.jar:na]
	at org.jboss.tools.usage.event.UsageReporter$6.run(UsageReporter.java:364) [org.jboss.tools.usage_2.1.1.Final-v20160408-2358-B112.jar:na]
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162) [org.eclipse.ui.workbench_3.107.1.v20160120-2131.jar:na]
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154) [org.eclipse.ui.workbench_3.107.1.v20160120-2131.jar:na]
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35) [org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar:na]
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135) [org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar:na]
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4155) [org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3772) [org.eclipse.swt.win32.win32.x86_64_3.104.2.v20160212-1350.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337) [org.eclipse.core.databinding.observable_1.5.0.v20150422-0725.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156) [org.eclipse.e4.ui.workbench_1.3.1.v20160203-0951.jar:na]
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694) [org.eclipse.ui.workbench_3.107.1.v20160120-2131.jar:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337) [org.eclipse.core.databinding.observable_1.5.0.v20150422-0725.jar:na]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606) [org.eclipse.ui.workbench_3.107.1.v20160120-2131.jar:na]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150) [org.eclipse.ui.workbench_3.107.1.v20160120-2131.jar:na]
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139) [org.eclipse.ui.ide.application_1.1.0.v20150422-0725.jar:na]
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:54) [org.eclipse.pde.junit.runtime_3.4.500.v20150423-1241.jar:na]
	at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(UITestApplication.java:47) [org.eclipse.pde.junit.runtime_3.4.500.v20150423-1241.jar:na]
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:48) [org.eclipse.pde.junit.runtime_3.4.500.v20150423-1241.jar:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) [org.eclipse.equinox.app_1.3.300.v20150423-1356.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) [org.eclipse.osgi_3.10.102.v20160118-1700.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) [org.eclipse.osgi_3.10.102.v20160118-1700.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380) [org.eclipse.osgi_3.10.102.v20160118-1700.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235) [org.eclipse.osgi_3.10.102.v20160118-1700.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91-3-redhat]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91-3-redhat]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91-3-redhat]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91-3-redhat]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669) [org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608) [org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515) [org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar:na]
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488) [org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar:na]

**Comment by apupier** [comment]
The WebProjectConfigurator seems to have an issue, the list of actions that he tries to do is:
[VERSION_CHANGE[java 1.8], UNINSTALL[java 1.4], UNINSTALL[jst.utility 1.0], INSTALL[jst.web 3.0]]
so when trying to uninstalling the java 1.4, it doesn't exists anymore

**Comment by bfitzpat** [comment]
Interesting. I was reading through your comments and got to the WebProjectConfigurator wondering what I did to it... is there something we can do in the pom itself to step around this problem I wonder?

**Comment by apupier** [comment]
@bfitzpat I don't think so. We need to fix it in m2e-wtp. I have a proposal almost ready for that. But we will need to see the policy to integrate a patch fragment in our product.

**Comment by bfitzpat** [comment]
Lovely. Thanks for diving into this.

**Comment by apupier** [comment]
here is the related bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=500197 and the related gerrit-change https://git.eclipse.org/r/#/c/79617/

**Comment by bfitzpat** [comment]
Looks like you've been chatting with Max about it, so hopefully we can get it remedied quickly.

**Comment by lhein** [comment]
@apupier is the PR good to merge now?

**Comment by lhein** [comment]
testPR

**Comment by apupier** [comment]
no need to have the updated PR

**Comment by apupier** [comment]
Here is the JBoss TP update Jira issue to browse: https://issues.jboss.org/browse/JBTIS-844

**Comment by lhein** [comment]
Please close if no longer needed.

**Comment by apupier** [comment]
it is needed to reactivate the test when we will have integrated the m2e-wtp fix

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
Ok, i reproduced the issue but only when launching the test using maven command. Launching the test directly in Eclipse  is working.
I will investigate on it

**Comment by apupier** [comment]
test PR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by lhein** [comment]
+1

**Pull request merged**
