### PR TITLE
FUSETOOLS-2102 - replacing assembly plugin with truezip plugin

### PR DESCRIPTION
**Pull request by lhein**

### CODE REVIEW

**Comment by apupier** [comment]
we need to remove the currently commited zipped templates (and/or readd the .gitignore )

**Comment by apupier** [comment]
Why do we have skip set to true for maven-clean-plugin?
it was here before but shouldn't we remove it now?

**Comment by lhein** [comment]
we can remove the skip I guess

**Comment by lhein** [comment]
ok, still failing tests. will look at it next week.

**Comment by lhein** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
+1

**Pull request merged**
