### PR TITLE
FUSETOOLS-2018 - Have dependency on latest m2e tycho connectors

### PR DESCRIPTION
**Pull request by apupier**
- use latest IS TP with m2e tycho connector 0.9 which supports
generation of MANIFEST.MF
- remove ignore lifecycle mapping on maven-bundle-plugin

--> not able to test it fully yet because I have issues with my Target Platforms

### CODE REVIEW

**Comment by apupier** [comment]
testPR

**Comment by bfitzpat** [comment]
+1

**Comment by bfitzpat** [comment]
I'm getting a constraint issue - http://up1-qa.itos.redhat.com/#wB42OiEzg9LU3slEcoi1fg

**Comment by apupier** [comment]
I fixed the Launched configuration (for the constraint issue)
everything seems to work fine (after I tweaked the SY project repositories)

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
@bfitzpat  I think that I can't count your initial +1 as you reported an issue just after.

**Comment by lhein** [comment]
+1

**Pull request merged**
