### PR TITLE
Fusetools 1867

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
the build is currently failing because the latest artifact cannot be resolved:

[ERROR] Plugin org.apache.camel:camel-maven-plugin:2.17.0.redhat-630187 or one of its dependencies could not be resolved: Failure to find org.apache.camel:camel-maven-plugin:jar:2.17.0.redhat-630187 in http://repository.jboss.org/nexus/content/groups/m2-release-proxy was cached in the local repository, resolution will not be reattempted until the update interval of release-proxy.fusesource.org has elapsed or updates are forced -> [Help 1]

**Comment by lhein** [comment]
you need a settings.xml entry to get access to it.

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
the last build failed with some compilation issues in jmx activeMQ plugin....

**Comment by apupier** [comment]
I can reproduce the compilation failure with Maven Tycho after cleaning the project.
What can cause that? The activemq-osgi jar has been modified and doesn't export correctly the required packages? What else can be possible?

**Pull request merged**
