### PR TITLE
JBTIS-844 - update fuse tooling to 4.3.3.Final and tycho to 0.26

### PR DESCRIPTION
**Pull request by pleacu**
@lhein @apupier - this works for me - cleaned out my local m2 repo and build fuse tooling and the fuse TP

### CODE REVIEW

**Comment by lhein** [comment]
It seems Jenkins has a different opinion :)

**Comment by apupier** [comment]
testPR

**Comment by apupier** [comment]
on which maven repo is supposed to be the org.jboss.tools.integration-stack:target-platform:target:base-ea:4.3.3.Final ?
@pleacu maybe you have a specific repo in your .settings which is missing in our pom.xml

**Comment by apupier** [comment]
so after i relaunched it, it works, so maybe the repo was down the first time.

**Comment by apupier** [comment]
I merge this PR in order to go further with EAP tests locally.
If someone want to update the TP locally, he needs to use the 4.3.4-SNAPSHOT version for now. @pleacu will provide a 4.3.4.Final soon I suppose.

**Pull request merged**
