### PR TITLE
ENTESB-5845: make activemq templates working on runtime

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by apupier** [comment]
Can you rename the commit message which is currently three times repeated same sentence?
(if you can rebase on master at the same time, it will be perfect)

**Comment by lburgazzoli** [comment]
@apupier done

**Comment by apupier** [comment]
@lburgazzoli thx.
I created a PR on your branch based on the comments that i previously done on the commit itself, see https://github.com/lburgazzoli/fusesource-fuseide/pull/1
after that I think we can merge this PR.
I'm still a bit worried about the need to create a fiel in Fuse Runtime itself but we will see how to make it user-friendly in a second time

**Comment by apupier** [comment]
+1 for integrating in code base then I will work on another PR to integrate it in Fuse Tooling Template framework

**Comment by apupier** [comment]
+1
To integrate fully the AMQ templates, there is still some work to do but they are relted to Fuse Tooling itself, not the template itself

**Comment by apupier** [comment]
@lburgazzoli thank you for the help to provide this template

**Pull request merged**
