### PR TITLE
Fusetools 1914 reactivate java build to test on ci after several f ix

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
1 success, yeah! let's try several times
testPR

**Comment by apupier** [comment]
2 success, yeah! let's try several times
testPR

**Comment by lhein** [comment]
2 successful tries locally

**Comment by apupier** [comment]
3 success, yeah! let's try several times
testPR

**Comment by apupier** [comment]
4 success
Can I merge it?

**Comment by lhein** [comment]
yes

**Pull request merged**
