### PR TITLE
FUSETOOLS-1655 - Include tests into update site

### PR DESCRIPTION
**Pull request by apupier**
- create a feature for core tests
- the goal is to reuse rules in SAP Tooling project
- No unit tests due to limitation of fragment use

### CODE REVIEW

**Comment by lhein** [comment]
Why do you want to make the tests available in the update site?

**Comment by apupier** [comment]
I have two reasons:
- have acces to some Rules inside SAP Tooling
- start to publish tests as explained here https://github.com/jbosstools/jbosstools-devdoc/blob/master/source/how_to_add_a_test_plugin_or_feature.adoc but in fact seems to be in a separate update site

it seems that I would need more work for this and provide a separate Update Site for the test, need also to check how and where publish it

**Comment by apupier** [comment]
In  https://github.com/jbosstools/jbosstools-devdoc/blob/master/source/how_to_add_a_test_plugin_or_feature.adoc , there are mentions only of the aggregate site of JBoss Tools. there is nothing about the integration stack.
For integrations tack, includign Fuse, it seems that there is https://github.com/jbosstools/jbosstools-integration-stack/blob/master/devstudio/site-ea/category.xml but there is no test yet, will it be the right place? What is the exact link with the update site in our project?
@pleacu maybe you have a more precise idea?

**Comment by apupier** [comment]
after more search, it seems that we should no tuse the integration stack. in fact SAP Tooling is directly linked to Fuse Tooling update site, so we can add th etest on the update site and point SAP tooling to it, which will be http://download.jboss.org/jbosstools/snapshots/builds/Fuse-Tooling/all/repo/ (currently http://download.jboss.org/jbosstools/mars/development/updates/integration-stack/fuse-tooling/8.0.0.Beta2/all/repo )

**Comment by lhein** [comment]
I'd like to hide test features from the users which download/install from the update site. I guess thats also the reason why JBT has a dedicated update site for tests.

**Comment by pleacu** [comment]
Agreed.  Under fuse tooling is the place for it.
               --paull



----- Original Message -----

**Pull request closed without merging**
