### PR TITLE
FUSETOOLS-1824 - extracted xml catalog generator code into own maven module

### PR DESCRIPTION
**Pull request by lhein**

### CODE REVIEW

**Comment by apupier** [comment]
Shouldn't we delete the old files? (if I understood well, the code has just been moved in a separate module)

**Comment by lhein** [comment]
we could delete it now or we can just delete it all together later on. That doesn't really matter.

**Comment by apupier** [comment]
if it is possible now, i would prefer. it will help to check that the code has just moved and nothing has changed inside.

**Comment by lhein** [comment]
deleted the old one

**Pull request merged**
