### PR TITLE
Normalize all the line endings

### PR DESCRIPTION
**Pull request by apupier**
use Linux style

need to check that we have the correct result with this PR

### CODE REVIEW

**Comment by apupier** [comment]
I created https://github.com/apupier/fuseide/pull/3 to try to check for line endings but seems that it is not doing the trick

**Comment by lhein** [comment]
can you check your ~/.gitconfig file?

mine contains:

[core]
      	autocrlf = false
        safecrlf = true

**Comment by apupier** [comment]
I have (as I configured previously)
[core]
	autocrlf = true

**Comment by lhein** [comment]
please try my settings

**Comment by apupier** [comment]
configuration is platform-dependent: https://help.github.com/articles/dealing-with-line-endings/#global-settings-for-line-endings

**Comment by lhein** [comment]
Maybe we should create a .gitattributes files per repository which handles the correct line ending?

**Comment by apupier** [comment]
we will need to investigate how to configure the .gitattributes for the repository.
This PR seems to fix my issue after i recreated the other PR: https://github.com/apupier/fuseide/pull/4

**Pull request merged**
